### PR TITLE
`web_accessible` context

### LINKED ISSUE #35: Add support for `web_accessible_resources` contexts
**Usecase**

You have an extension with html files added to `web_accessible_resources` in the manifest. These pages should be allowed to communicate with the background script and other pages, similarly to how for e.g. the `popup` page can communicate with the background script.

**The problem**

`webext-bridge` currently does not treat these pages from `web_accessible_resources` as different contexts, rather it detects them as `background` contexts. This prevents them to communicate with the background script, even through there is no security risk here, as the `browser.runtime.sendMessage`/`browser.runtime.onMessage` APIs are already exposed to them.

**Potential solution**

Create a new type of context (e.g.: `web_accessible`) that behaves similarly to how the `content-script` contexts work. There could be multiple pages added to `web_accessible_resources`, so this would allow you to send messages to specific pages as well, using their `tabId`.

**Example**

Send a message to a page with "`web_accessible`" context and the tabId `3412`:

```ts
const returnData = await sendMessage('bar', { /* ... */ }, "web_accessible@3412");
```

### PR DESCRIPTION
**Pull request by martonlederer**
Closes #35 and #12

- Adds `web_accessible` context for pages in `web_accessible_resources`
- Fixes communication between the background script and `web_accessible_resources` pages
- Fixes invalid context type (`background`) with messages from `web_accessible_resources` pages
- Adds documentation about the new context

### CODE REVIEW

**Comment by martonlederer** [comment]
✅ Ready for review + tested with `onMessage` and `sendMessage` (with tabId as destination)

**Comment by thanhlmm** [comment]
Hi @zikaari, what needs to be done to make this MR merged? We also have this issue and want to fix it asap

**Comment by martonlederer** [comment]
The pr is ready, but it doesn't seem like the developer os merging a lot of prs. Let's hope it gets merged asap :)

**Comment by thanhlmm** [comment]
Hi @zikaari , can we move this PR forward?

**Comment by zikaari** [comment]
Apologies for the long delay folks, I've been working on a [very important problem](https://github.com/zikaari/webext-bridge/pull/38) with `webext-bridge`.

@martonlederer Thank you the effort! `v5.0.0` is no longer under development, please use the new framework available in `next` branch of this repo. Fortunately it is actually less work than what you have done already.

It is as simple as `createEndpointRuntime('<endpoint_name>', <routing handler>)`, see implementation for [popup ](https://github.com/zikaari/webext-bridge/blob/e4e5f4900955c610b4f8b1c9e93940f4d17ceb56/src/popup.ts) or [window ](https://github.com/zikaari/webext-bridge/blob/0e011a3ca133699d54acda5578d808996facd822/src/window.ts) as a reference.

**Comment by martonlederer** [comment]
Wow thank you! That's amazing

**Comment by zikaari** [comment]
@martonlederer You dropped the PR, Is it working with `next` branch somehow?

**Comment by martonlederer** [comment]
@zikaari haven't been able to test that yet, I didn't have time to update my extension with it, so rn I just published my patch to npm, so it works temporary. Once I'm done with everything else, I'm gonna try and test it :)

**Comment by thanhlmm** [comment]
Hi @martonlederer, I wonder that can you share your publishing package? I need it on my project as well

Thank you for your hard work

**Pull request closed without merging**
